# Generated by Django 2.0 on 2018-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semver',
            name='major',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
