# Generated by Django 2.0 on 2018-05-22 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdd', '0002_semver_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semver',
            name='major',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
