# Generated by Django 2.0 on 2018-05-22 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tdd', '0003_auto_20180522_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='semver',
            name='minor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='semver',
            name='major',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
